### ISSUE TITLE
poco 1.7 ?

### ISSUE THREAD

**Issue by KrisBuytaert** [hdezela/loolwsd-rpm#1]
Not so much an issue but can you document where you found 
poco-devel  >= 1.7  ? for CentOS 7 ?

**Comment by hdezela** [comment]
It's right here on github [poco releases](https://github.com/pocoproject/poco/releases), you can either use my spec file to build it or mangle the [Fedora SRPM](https://pkgs.org/fedora-rawhide/fedora-x86_64/poco-devel-1.7.3-5.fc25.x86_64.rpm.html) for CentOS.

**Comment by KrisBuytaert** [comment]
Need my morning coffee .. failed to notice the spec file right next to it ;( 
Thnx for the quick response however !
